/* ============================================
   闪电充电 v2.0 - 模拟数据层
   模拟真实充电平台数据模型
   ============================================ */

const MockData = {
  // 用户信息
  user: {
    id: 'U10086',
    name: '张明远',
    phone: '138****6789',
    avatar: null,
    balance: 286.50,
    memberLevel: 3,
    memberName: '黄金会员',
    points: 2840,
    totalCharged: 1248.6,
    totalOrders: 47,
    carbonSaved: 523.8,
    joinDate: '2023-08-15',
    vehicles: [
      {
        id: 1,
        brand: '比亚迪 汉 EV',
        plate: '粤B·D12345',
        batteryCapacity: 76.9,
        currentCharge: 62,
        color: '#1565c0',
      },
      {
        id: 2,
        brand: '特斯拉 Model 3',
        plate: '粤B·A67890',
        batteryCapacity: 60.0,
        currentCharge: 35,
        color: '#e65100',
      },
    ],
  },

  // 充电站数据（模拟真实坐标 - 深圳南山区）
  stations: [
    {
      id: 1,
      name: '特来电超级充电站（科技园店）',
      address: '深圳市南山区科技园南路18号科兴科学园B2',
      distance: 0.8,
      lat: 22.5362,
      lng: 113.9527,
      price: 1.25,
      total: 20,
      available: 8,
      rating: 4.8,
      tags: ['24小时', '休息室', '卫生间', 'WiFi'],
      operator: '特来电',
      openTime: '全天24小时',
      chargers: [
        { id: 'A01', type: 'fast', power: '120kW', status: 'available', price: 1.25, connector: 'GB/T' },
        { id: 'A02', type: 'fast', power: '120kW', status: 'available', price: 1.25, connector: 'GB/T' },
        { id: 'A03', type: 'fast', power: '120kW', status: 'charging', price: 1.25, connector: 'GB/T' },
        { id: 'A04', type: 'fast', power: '120kW', status: 'available', price: 1.25, connector: 'GB/T' },
        { id: 'A05', type: 'fast', power: '120kW', status: 'offline', price: 1.25, connector: 'GB/T' },
        { id: 'B01', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'B02', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'B03', type: 'slow', power: '7kW', status: 'charging', price: 0.85, connector: 'GB/T' },
        { id: 'B04', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'B05', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'B06', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'B07', type: 'slow', power: '7kW', status: 'offline', price: 0.85, connector: 'GB/T' },
        { id: 'B08', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'B09', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'B10', type: 'slow', power: '7kW', status: 'available', price: 0.85, connector: 'GB/T' },
        { id: 'C01', type: 'fast', power: '60kW', status: 'available', price: 1.15, connector: 'GB/T' },
        { id: 'C02', type: 'fast', power: '60kW', status: 'charging', price: 1.15, connector: 'GB/T' },
        { id: 'C03', type: 'fast', power: '60kW', status: 'available', price: 1.15, connector: 'GB/T' },
        { id: 'C04', type: 'fast', power: '60kW', status: 'available', price: 1.15, connector: 'GB/T' },
        { id: 'C05', type: 'fast', power: '60kW', status: 'available', price: 1.15, connector: 'GB/T' },
      ],
    },
    {
      id: 2,
      name: '星星充电（万象天地站）',
      address: '深圳市南山区深南大道9668号万象天地B2层',
      distance: 1.5,
      lat: 22.5370,
      lng: 113.9550,
      price: 1.38,
      total: 12,
      available: 3,
      rating: 4.6,
      tags: ['商场', '餐饮', '免费停车2h'],
      operator: '星星充电',
      openTime: '10:00-22:00',
      chargers: [
        { id: 'D01', type: 'fast', power: '150kW', status: 'available', price: 1.38, connector: 'GB/T' },
        { id: 'D02', type: 'fast', power: '150kW', status: 'charging', price: 1.38, connector: 'GB/T' },
        { id: 'D03', type: 'fast', power: '150kW', status: 'charging', price: 1.38, connector: 'GB/T' },
        { id: 'D04', type: 'fast', power: '150kW', status: 'charging', price: 1.38, connector: 'GB/T' },
        { id: 'D05', type: 'fast', power: '150kW', status: 'available', price: 1.38, connector: 'GB/T' },
        { id: 'D06', type: 'fast', power: '150kW', status: 'charging', price: 1.38, connector: 'GB/T' },
        { id: 'E01', type: 'slow', power: '7kW', status: 'charging', price: 0.95, connector: 'GB/T' },
        { id: 'E02', type: 'slow', power: '7kW', status: 'available', price: 0.95, connector: 'GB/T' },
        { id: 'E03', type: 'slow', power: '7kW', status: 'charging', price: 0.95, connector: 'GB/T' },
        { id: 'E04', type: 'slow', power: '7kW', status: 'charging', price: 0.95, connector: 'GB/T' },
        { id: 'E05', type: 'slow', power: '7kW', status: 'charging', price: 0.95, connector: 'GB/T' },
        { id: 'E06', type: 'slow', power: '7kW', status: 'offline', price: 0.95, connector: 'GB/T' },
      ],
    },
    {
      id: 3,
      name: '国家电网充电站（高新园站）',
      address: '深圳市南山区高新南一道2号TCL大厦旁',
      distance: 2.1,
      lat: 22.5400,
      lng: 113.9500,
      price: 1.08,
      total: 16,
      available: 12,
      rating: 4.5,
      tags: ['国网', '即插即充', '峰谷电价'],
      operator: '国家电网',
      openTime: '全天24小时',
      chargers: [
        { id: 'F01', type: 'fast', power: '60kW', status: 'available', price: 1.08, connector: 'GB/T' },
        { id: 'F02', type: 'fast', power: '60kW', status: 'available', price: 1.08, connector: 'GB/T' },
        { id: 'F03', type: 'fast', power: '60kW', status: 'available', price: 1.08, connector: 'GB/T' },
        { id: 'F04', type: 'fast', power: '60kW', status: 'available', price: 1.08, connector: 'GB/T' },
        { id: 'F05', type: 'fast', power: '60kW', status: 'charging', price: 1.08, connector: 'GB/T' },
        { id: 'F06', type: 'fast', power: '60kW', status: 'available', price: 1.08, connector: 'GB/T' },
        { id: 'F07', type: 'fast', power: '60kW', status: 'available', price: 1.08, connector: 'GB/T' },
        { id: 'F08', type: 'fast', power: '60kW', status: 'available', price: 1.08, connector: 'GB/T' },
        { id: 'G01', type: 'slow', power: '7kW', status: 'available', price: 0.68, connector: 'GB/T' },
        { id: 'G02', type: 'slow', power: '7kW', status: 'available', price: 0.68, connector: 'GB/T' },
        { id: 'G03', type: 'slow', power: '7kW', status: 'available', price: 0.68, connector: 'GB/T' },
        { id: 'G04', type: 'slow', power: '7kW', status: 'offline', price: 0.68, connector: 'GB/T' },
        { id: 'G05', type: 'slow', power: '7kW', status: 'available', price: 0.68, connector: 'GB/T' },
        { id: 'G06', type: 'slow', power: '7kW', status: 'available', price: 0.68, connector: 'GB/T' },
        { id: 'G07', type: 'slow', power: '7kW', status: 'available', price: 0.68, connector: 'GB/T' },
        { id: 'G08', type: 'slow', power: '7kW', status: 'available', price: 0.68, connector: 'GB/T' },
      ],
    },
    {
      id: 4,
      name: '小桔充电（海岸城站）',
      address: '深圳市南山区文心五路33号海岸城B1',
      distance: 3.2,
      lat: 22.5180,
      lng: 113.9370,
      price: 1.45,
      total: 8,
      available: 1,
      rating: 4.3,
      tags: ['商圈', '超快充', 'VIP休息区'],
      operator: '小桔充电',
      openTime: '08:00-23:00',
      chargers: [
        { id: 'H01', type: 'fast', power: '180kW', status: 'charging', price: 1.45, connector: 'CCS2' },
        { id: 'H02', type: 'fast', power: '180kW', status: 'charging', price: 1.45, connector: 'CCS2' },
        { id: 'H03', type: 'fast', power: '180kW', status: 'charging', price: 1.45, connector: 'CCS2' },
        { id: 'H04', type: 'fast', power: '180kW', status: 'charging', price: 1.45, connector: 'CCS2' },
        { id: 'H05', type: 'fast', power: '180kW', status: 'available', price: 1.45, connector: 'CCS2' },
        { id: 'H06', type: 'fast', power: '180kW', status: 'charging', price: 1.45, connector: 'CCS2' },
        { id: 'H07', type: 'fast', power: '180kW', status: 'charging', price: 1.45, connector: 'CCS2' },
        { id: 'H08', type: 'fast', power: '180kW', status: 'offline', price: 1.45, connector: 'CCS2' },
      ],
    },
    {
      id: 5,
      name: '云快充（深圳湾体育中心站）',
      address: '深圳市南山区滨海大道3001号',
      distance: 4.0,
      lat: 22.5185,
      lng: 113.9480,
      price: 1.18,
      total: 10,
      available: 6,
      rating: 4.4,
      tags: ['大型停车场', '24小时', '洗车服务'],
      operator: '云快充',
      openTime: '全天24小时',
      chargers: [
        { id: 'I01', type: 'fast', power: '120kW', status: 'available', price: 1.18, connector: 'GB/T' },
        { id: 'I02', type: 'fast', power: '120kW', status: 'available', price: 1.18, connector: 'GB/T' },
        { id: 'I03', type: 'fast', power: '120kW', status: 'available', price: 1.18, connector: 'GB/T' },
        { id: 'I04', type: 'fast', power: '120kW', status: 'charging', price: 1.18, connector: 'GB/T' },
        { id: 'I05', type: 'fast', power: '120kW', status: 'charging', price: 1.18, connector: 'GB/T' },
        { id: 'J01', type: 'slow', power: '7kW', status: 'available', price: 0.78, connector: 'GB/T' },
        { id: 'J02', type: 'slow', power: '7kW', status: 'available', price: 0.78, connector: 'GB/T' },
        { id: 'J03', type: 'slow', power: '7kW', status: 'charging', price: 0.78, connector: 'GB/T' },
        { id: 'J04', type: 'slow', power: '7kW', status: 'charging', price: 0.78, connector: 'GB/T' },
        { id: 'J05', type: 'slow', power: '7kW', status: 'available', price: 0.78, connector: 'GB/T' },
      ],
    },
  ],

  // 历史订单（带完整时间线）
  orders: [
    {
      id: '20240623001',
      stationName: '特来电超级充电站（科技园店）',
      chargerId: 'A03',
      chargerType: 'fast',
      power: '120kW',
      startTime: '2024-06-23T18:30:00',
      endTime: '2024-06-23T19:15:00',
      duration: 45,
      energy: 28.6,
      price: 1.25,
      amount: 35.75,
      couponAmount: 0,
      actualPay: 35.75,
      status: 'completed',
      payMethod: '余额',
    },
    {
      id: '20240622001',
      stationName: '星星充电（万象天地站）',
      chargerId: 'D02',
      chargerType: 'fast',
      power: '150kW',
      startTime: '2024-06-22T12:00:00',
      endTime: '2024-06-22T12:52:00',
      duration: 52,
      energy: 35.2,
      price: 1.38,
      amount: 48.58,
      couponAmount: 5,
      actualPay: 43.58,
      status: 'completed',
      payMethod: '余额',
    },
    {
      id: '20240620001',
      stationName: '国家电网充电站（高新园站）',
      chargerId: 'F05',
      chargerType: 'fast',
      power: '60kW',
      startTime: '2024-06-20T09:15:00',
      endTime: '2024-06-20T10:05:00',
      duration: 50,
      energy: 32.0,
      price: 1.08,
      amount: 34.56,
      couponAmount: 0,
      actualPay: 34.56,
      status: 'completed',
      payMethod: '微信支付',
    },
    {
      id: '20240618001',
      stationName: '小桔充电（海岸城站）',
      chargerId: 'H05',
      chargerType: 'fast',
      power: '180kW',
      startTime: '2024-06-18T20:00:00',
      endTime: '2024-06-18T20:35:00',
      duration: 35,
      energy: 22.8,
      price: 1.45,
      amount: 33.06,
      couponAmount: 8,
      actualPay: 25.06,
      status: 'completed',
      payMethod: '余额',
    },
    {
      id: '20240615001',
      stationName: '云快充（深圳湾体育中心站）',
      chargerId: 'I04',
      chargerType: 'fast',
      power: '120kW',
      startTime: '2024-06-15T14:20:00',
      endTime: '2024-06-15T15:10:00',
      duration: 50,
      energy: 31.5,
      price: 1.18,
      amount: 37.17,
      couponAmount: 0,
      actualPay: 37.17,
      status: 'completed',
      payMethod: '余额',
    },
    {
      id: '20240623002',
      stationName: '特来电超级充电站（科技园店）',
      chargerId: 'A01',
      chargerType: 'fast',
      power: '120kW',
      startTime: '2024-06-23T22:10:00',
      duration: 0,
      energy: 0,
      price: 1.25,
      amount: 0,
      couponAmount: 0,
      actualPay: 0,
      status: 'ongoing',
      payMethod: '余额',
    },
  ],

  // 优惠券
  coupons: [
    { id: 1, name: '新用户专享券', type: 'discount', amount: 5, minAmount: 20, expireDate: '2024-07-31', used: false },
    { id: 2, name: '充电满30减8', type: 'discount', amount: 8, minAmount: 30, expireDate: '2024-07-15', used: false },
    { id: 3, name: '夜间充电9折', type: 'rate', amount: 0, discount: 0.9, minAmount: 0, expireDate: '2024-08-01', used: false },
    { id: 4, name: '周末充电满减', type: 'discount', amount: 10, minAmount: 50, expireDate: '2024-06-30', used: false },
    { id: 5, name: '老友邀请券', type: 'discount', amount: 3, minAmount: 15, expireDate: '2024-07-20', used: true },
  ],

  // 发票记录
  invoices: [
    { id: 'INV202406001', orderId: '20240623001', amount: 35.75, company: '深圳科技有限公司', date: '2024-06-23', type: '电子发票' },
    { id: 'INV202406002', orderId: '20240622001', amount: 43.58, company: '个人', date: '2024-06-22', type: '电子发票' },
    { id: 'INV202406003', orderId: '20240620001', amount: 34.56, company: '个人', date: '2024-06-20', type: '电子发票' },
  ],

  // 系统公告
  notices: [
    '🔥 新用户注册即送5元充电券，邀请好友再得3元',
    '⚡ 科技园充电站新增10个快充桩，充电更便捷',
    '🎉 会员日每周三充电享9折优惠',
  ],
};
